remote_theme: allejo/jekyll-docs-theme@v1.0.0

name: SDSU's AI Club Workshops

ui:
  mode: 'light'
  
links: 
  header:
    - title: Github
      icon: github
      brand: true
      url: https://github.com/HectorENevarez/AIClubWorkshopsSpring21

social:
  github:
    user: HectorENevarez
    repo: AIClubWorkshopsSpring21
